server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${CENTRAL_LOKI_URL}
    # Basic auth for remote VPS (omit for VPC)
    basic_auth:
      username: ${BASIC_AUTH_USER}
      password: ${BASIC_AUTH_PASSWORD}

    # Batching configuration
    batchwait: 1s
    batchsize: 1048576  # 1MB

    # Retry configuration
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10

    # Timeout
    timeout: 10s

scrape_configs:
  # Scrape Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # Filter removed - collect logs from all containers
        # To filter specific containers, add label 'logging=promtail' to docker-compose

    # Relabel to set metadata
    relabel_configs:
      # Container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      # Container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'

      # Image name
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'

      # Host label (from environment variable)
      - replacement: '${HOSTNAME}'
        target_label: 'host'

      # Job label
      - replacement: 'docker'
        target_label: 'job'

    # Pipeline stages
    pipeline_stages:
      # Parse JSON logs if available
      - json:
          expressions:
            level: level
            msg: msg
            logger: logger
            timestamp: timestamp

      # Extract log level as label
      - labels:
          level:

      # Timestamp parsing
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Drop healthcheck logs (optional - uncomment to enable)
      # - match:
      #     selector: '{job="docker"}'
      #     stages:
      #       - drop:
      #           expression: ".*healthcheck.*"
      #       - drop:
      #           expression: ".*ping.*"

  # Optional: Scrape system logs
  # - job_name: syslog
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: syslog
  #         host: ${HOSTNAME}
  #         __path__: /var/log/syslog

  # Optional: Scrape custom application logs
  # - job_name: app-logs
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: app
  #         host: ${HOSTNAME}
  #         __path__: /var/log/app/*.log
